# Generated by Django 4.1.5 on 2023-01-13 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm_tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(validators=[django.core.validators.RegexValidator('[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[by]', code='Invalid email', message='Incorrect mail')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_]{6,10}$', code='Invalid login', message='Bad login')]),
        ),
    ]
