# Generated by Django 4.1.5 on 2023-01-22 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volkau_store', '0002_alter_category_created_at_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Game Name')),
                ('game_image', models.ImageField(upload_to='', verbose_name='Game Image')),
                ('description', models.CharField(max_length=140, verbose_name='Game Description')),
                ('release_date', models.DateField(verbose_name='Game Release')),
                ('public_date', models.DateField(auto_now_add=True, verbose_name='Game Public')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, max_length=4, verbose_name='Game Price')),
                ('is_active', models.BooleanField(verbose_name='Game is active?')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volkau_store.category', verbose_name='Game Category')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
