# Generated by Django 4.1.5 on 2023-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volkau_store', '0003_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_image',
            field=models.ImageField(upload_to='volkau_store/static/image', verbose_name='Game Image'),
        ),
    ]
