# Generated by Django 4.1.5 on 2023-01-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volkau_store', '0005_alter_games_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Game Description'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='game', verbose_name='Game Image'),
        ),
        migrations.AlterField(
            model_name='games',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Game active'),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Game Name'),
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Game Price'),
        ),
    ]
