# Generated by Django 4.1.5 on 2023-01-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volkau_store', '0006_alter_category_description_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='games_number',
            field=models.IntegerField(default=0, verbose_name='Games number'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='games',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
