# Generated by Django 4.1.5 on 2023-01-31 10:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volkau_store', '0006_alter_category_description_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='games_number',
            field=models.IntegerField(default=0, verbose_name='Games number'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='games',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Game Price'),
        ),
        migrations.AddIndex(
            model_name='games',
            index=models.Index(fields=['name'], name='games_names_idx'),
        ),
    ]
