# Generated by Django 4.1.5 on 2023-03-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volkau_store', '0011_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='username',
        ),
    ]
